%% Spillover compensation for Imaging Mass Cytometry (Spillover_compensation_ALS_HyperionXTi_func.m)
% -------------------------------------------------------------------------
% Platform   : HyperionXTi (Standard BioTools)
% Dataset    : ALS IMC dataset
% -------------------------------------------------------------------------
% Author     : Gen Ohtsuki
% Affiliation: Kyoto University 
% Since 2026-06-01
% Modified 2026-07-28
% Copyright (c) 2026 Gen Ohtsuki
%
% Associated publication:
% Hikosaka et al. in review
% "Glial metabolic states in human sporadic amyotrophic lateral sclerosis
% uncovered by spatial single-cell proteomics."
% -------------------------------------------------------------------------
% Description:
%   This function is called from "SOcorrection_all_csv_ALS_Hyperion.m",
%   which iterates over all files matching '*_SOc.csv' in folderPath.
% -------------------------------------------------------------------------
% Input:
%   spillover_matrix  : ChannelN x ChannelN spillover matrix (%)
%   IMCmeasured       : cellN x ChannelN matrix of single-cell intensity values
% Output:
%   compensated       : cellN x ChannelN matrix of spillover-compensated values
% -------------------------------------------------------------------------
% Requirements:
%    - Signal Overlap Matrix_ALS_Hyperion.xlsx
%    - keep4.m
% -------------------------------------------------------------------------

% clear all; 
keep4 folderPath SOc_files SOCorrection_folderPath inputFile_Name outputFile_Name...
    k size_roiFolders roiFolders
close all;
% clc;
warning('off');
scrsz = get(0,'ScreenSize');
curdir = pwd;

%% Read imc table

SOfilePath = fullfile(folderPath, inputFile_Name);
T = readtable(SOfilePath);

Signal_channelNames = { ...
'Cell_80ArAr', ...
'Cell_89Y_Collagen_I', ...
'Cell_115In_CD20', ...
'Cell_120Sn', ...
'Cell_127I', ...
'Cell_131Xe', ...
'Cell_134Xe', ...
'Cell_138Ba', ...
'Cell_141Pr_APP', ...
'Cell_142Nd_Iba1', ...
'Cell_143Nd_GFAP', ...
'Cell_144Nd_CD11b', ...
'Cell_145Nd_NeuN', ...
'Cell_146Nd_S100beta', ...
'Cell_147Sm_AQP4', ...
'Cell_148Nd_MAP2', ...
'Cell_149Sm_CX3CR1', ...
'Cell_150Nd_UBQLN2', ...
'Cell_151Eu_CD31', ...
'Cell_152Sm_ATXN2', ...
'Cell_153Eu_TREM2', ...
'Cell_154Sm_CD11c', ...
'Cell_155Gd_FoxP3', ...
'Cell_156Gd_CD4', ...
'Cell_158Gd_IL6ST', ...
'Cell_159Tb_p53', ...
'Cell_160Gd_CD66b', ...
'Cell_161Dy_TGFBR2', ...
'Cell_162Dy_CD8a', ...
'Cell_163Dy_pTDP43', ...
'Cell_164Dy_CLEC7A', ...
'Cell_165Ho_p21', ...
'Cell_166Er_GAD67', ...
'Cell_167Er_CD34', ...
'Cell_168Er_Olig2', ...
'Cell_169Tm_GLS', ...
'Cell_170Er_p16', ...
'Cell_171Yb_APOE', ...
'Cell_172Yb_FUS', ...
'Cell_173Yb_GLS2', ...
'Cell_174Yb_HLADR', ...
'Cell_175Lu_TDP43', ...
'Cell_176Yb_NRF2', ...
'Cell_191Ir_DNA1', ...
'Cell_193Ir_DNA2', ...
'Cell_195Pt_ICSK1', ...
'Cell_196Pt_ICSK2', ...
'Cell_198Pt_ICSK3', ...
'Cell_208Pb'};

% Rename table heads: 'Signal_X'
idx = startsWith(T.Properties.VariableNames,'Signal_');
T.Properties.VariableNames(idx) = Signal_channelNames;

outputFile = fullfile(folderPath, outputFile_Name);


channelNames = { ...
'Cell_89Y_Collagen_I', ...
'Cell_115In_CD20', ...
'Cell_141Pr_APP', ...
'Cell_142Nd_Iba1', ...
'Cell_143Nd_GFAP', ...
'Cell_144Nd_CD11b', ...
'Cell_145Nd_NeuN', ...
'Cell_146Nd_S100beta', ...
'Cell_147Sm_AQP4', ...
'Cell_148Nd_MAP2', ...
'Cell_149Sm_CX3CR1', ...
'Cell_150Nd_UBQLN2', ...
'Cell_151Eu_CD31', ...
'Cell_152Sm_ATXN2', ...
'Cell_153Eu_TREM2', ...
'Cell_154Sm_CD11c', ...
'Cell_155Gd_FoxP3', ...
'Cell_156Gd_CD4', ...
'Cell_158Gd_IL6ST', ...
'Cell_159Tb_p53', ...
'Cell_160Gd_CD66b', ...
'Cell_161Dy_TGFBR2', ...
'Cell_162Dy_CD8a', ...
'Cell_163Dy_pTDP43', ...
'Cell_164Dy_CLEC7A', ...
'Cell_165Ho_p21', ...
'Cell_166Er_GAD67', ...
'Cell_167Er_CD34', ...
'Cell_168Er_Olig2', ...
'Cell_169Tm_GLS', ...
'Cell_170Er_p16', ...
'Cell_171Yb_APOE', ...
'Cell_172Yb_FUS', ...
'Cell_173Yb_GLS2', ...
'Cell_174Yb_HLADR', ...
'Cell_175Lu_TDP43', ...
'Cell_176Yb_NRF2', ...
'Cell_191Ir_DNA1', ...
'Cell_193Ir_DNA2', ...
'Cell_195Pt_ICSK1', ...
'Cell_196Pt_ICSK2', ...
'Cell_198Pt_ICSK3'};

% Extract the channels as a table
T_channels = T(:, channelNames);

% Convert to numeric matrix (Ncells × NChannels)
IMCmeasured = T_channels{:,:};

%% Read SpillOver table of Hyperion 
SOCorrection_folderPath;
SOfilePath = fullfile(SOCorrection_folderPath, 'Signal Overlap Matrix_ALS_HypXTi.xlsx');

% Read cell E5:AH45
spillover_matrix = readmatrix(SOfilePath, 'Range', 'E5:AT46');


%% Convert percentages to fractions
SOcoeff = spillover_matrix / 100;

% Check matrix conditioning
cond_number = cond(SOcoeff);
fprintf('Condition number of spillover matrix = %.2f\n', cond_number);

if cond_number > 1e6
    warning('Spillover matrix is poorly conditioned.');
end

% -------------------------------------------------------------------------
% IMC Spillover Demixing
%
% IMCmeasured is a cellN x W x 30 IMC image stack
%   spillover_matrix   : 30 x 30 spillover matrix (%)
%
% Model:
%   Measured = True * SpilloverMatrix
%
% -------------------------------------------------------------------------

[cellN, Nchannels] = size(IMCmeasured);

assert(Nchannels == size(SOcoeff,1), ...
    'Number of channels does not match spillover matrix.');


%% ------------------------------------------------------------------------
% IMC Spillover Demixing Using NNLS
% -------------------------------------------------------------------------

% method: that solves a least squares problem using:
% (i) standard least squares (normal equations, A \ b)
% (ii) ridge regression (Tikhonov regularization)

method = 'ii';

Ytranspose = transpose(IMCmeasured);
Xt = Ytranspose;

opts = optimoptions('lsqnonlin', ...
    'Algorithm',     'levenberg-marquardt', ...
    'Display',       'final', ...
    'MaxIterations', 1000, ...
    'FunctionTolerance', 1e-10);

SOcoeff;

for p = 1:cellN

    y = double(Ytranspose(:,p));
    valid = ~isnan(y); %% NaN treatment for IMC 
    x = y;

  switch method
    case 'i' % 'i' = standard least squares
        x_lsq_valid = lsqnonneg(SOcoeff(valid,valid), y(valid), opts);
    case 'ii' % 'ii' = ridge regression
        lambda = 0.05; % Regulation parameter (0.001 - 0.1)
        A_R = [SOcoeff(valid,valid); lambda*eye(nnz(valid))];
        b_R = [y(valid); zeros(nnz(valid),1)];
        limit_regulation = 0.7; % Parameter to limit the subtraction, 70%. 
        x_lsq_valid_Tik = lsqnonneg(A_R, b_R);
        %[x x_lsq_valid x_lsq_valid_Tik]
        x_lsq_valid = max(x_lsq_valid_Tik, (1-limit_regulation)*y(valid));
  end

    if nnz(valid) < Nchannels
        x(valid) = x_lsq_valid;
        x(~valid) = NaN;
        x_lsq_valid = x;
    end

    Xt(:,p) = single(x_lsq_valid);

end

demixed_image = transpose(Xt);

fprintf('NNLS demixing completed.\n');

% % Double Check % %
% Signal values
IMCmeasured(1:5,:)
demixed_image(1:5,:)
D_demixed = IMCmeasured-demixed_image;
D_demixed(1:5,:)
% Reduction rates, > 0.3
ratio = mean(demixed_image,"omitnan")./mean(IMCmeasured,"omitnan");
table((1:Nchannels)', ratio')

%% Replace columns C:AF with demixed_image
if size(demixed_image,1) ~= height(T)
    error('Number of rows in demixed_image does not match table height.');
end

if size(demixed_image,2) ~= Nchannels
    error(['demixed_image must have ' num2str(Nchannels) ' columns.']);
end

% T_out{:,3:(Nchannels+2)} = demixed_image;
T_out = [T(:,1:9) T_channels]; %AD HyperionXTi 20260714
T_out{:,10:(Nchannels+10-1)} = demixed_image;

%% Save
writetable(T_out, outputFile);
fprintf('Saved:\n%s\n', outputFile);
